parameters:
  uploads_directory: "%kernel.project_dir%/assets/uploads"
  upload_directory: "%kernel.project_dir%/public/uploads/images"
  diplomes_directory: "%kernel.project_dir%/public/uploads/diplomes"
  images_directory: "%kernel.project_dir%/public/uploads/images"
  app.sendgrid.api_key: "%env(SENDGRID_API_KEY)%"
  app.sendgrid.sender_email: "%env(SENDGRID_SENDER_EMAIL)%"
  app.sendgrid.sender_name: "%env(SENDGRID_SENDER_NAME)%"
  google_recaptcha_site_key: "%env(GOOGLE_RECAPTCHA_SITE_KEY)%"
  known_faces_directory: "C:\\Users\\LENOVO\\Desktop\\Reconnaissance Facile\\code\\code\\known_faces"
  twilio_account_sid: "%env(twilio_account_sid)%"
  twilio_auth_token: "%env(twilio_auth_token)%"
  twilio_from_number: "%env(twilio_from_number)%"
  twilio_to_number: "%env(twilio_to_number)%"
  signatures_directory: '%kernel.project_dir%/public/uploads/signatures'
  google_credentials_path: '%kernel.project_dir%/config/google_credentials.json'
  google_token_path: '%kernel.project_dir%/var/google_token.json'

services:
  # Default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # Déclaration spécifique de MailService
  App\Service\MailService:
    arguments:
      $mailer: "@mailer.mailer"
      $twig: "@twig"

  # Makes classes in src/ available to be used as services
  # This creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  App\Service\CartService:
    arguments:
      $requestStack: "@request_stack"

  App\Service\EmailService:
    arguments:
      $apiKey: "%env(SENDGRID_API_KEY)%"
      $senderEmail: "%env(SENDGRID_SENDER_EMAIL)%"
      $senderName: "%env(SENDGRID_SENDER_NAME)%"
